### ISSUE TITLE
“Quang Cao & Rao Vat” should have different filters on the left.

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#100]
```
Restaurants, Automotive, Health & Wellness, Attorneys, Shopping, Beauty & Spas, Professional Services, Home Improvement, Real Estate, Hotel & Travel, Financial Services, Nightlife,  All Others
```

**Comment by denisha-addweb** [comment]
We require inputs regarding mock up shared for “Quang Cao & Rao Vat” page.

**Comment by atlantaluck** [comment]
The mockup is approved.

**Comment by atlantaluck** [comment]
![pasted image at 2016_03_12 01_11 pm](https://cloud.githubusercontent.com/assets/17599998/14553133/202cc95c-02b2-11e6-872a-a8fad8d3ad1e.png)

**Comment by atlantaluck** [comment]
regarding the mockup.  
1. "newberry, 10 chairs" is the title.  there should be no address under the title.
2. All the space from "khu vuc" thru the "sale price" are for the message.

**Comment by Deepali-AddWeb** [comment]
Please elaborate on 2nd point - All the space from "khu vuc" thru the "sale price" are for the message.

**Comment by atlantaluck** [comment]
I'm sending 2 pictures. First one was the template approved previously with the "title" and "description" and "contact information".  But, I have agree also that we can use the second template that you sent me.  The only change need to be made is to get rid of the middle field a replace it with a description.
![quang can rao vat](https://cloud.githubusercontent.com/assets/17599998/14626083/77eff234-05b6-11e6-9041-6b5e03f93d54.jpg)

2nd. revised.
![rao vat approved revised](https://cloud.githubusercontent.com/assets/17599998/14626146/0af06dca-05b7-11e6-8550-961df872baef.png)

**Comment by saurabhd** [comment]
I think the mockup you provided before and the current mockup attached is different. 

This would take 1 hour of time estimates to accomplish. Need your approval.

**Comment by atlantaluck** [comment]
The most important is the title and the main area for the description.

**Comment by atlantaluck** [comment]
approved

**Comment by atlantaluck** [comment]
Please, make the description box look blend in with all the colors background and theme.  The pictures I provided are just example and I created using MS Paint.  Thank you

**Comment by atlantaluck** [comment]
Do we have an individual page for the Quang Cao & Rao Vat?

**Comment by denisha-addweb** [comment]
yes
