### ISSUE TITLE
Image gallery.  image thumb and actual image are not display properly

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#105]
Image gallery: It is not display the correct full image the customer uploaded. Let’s say if a customer uploaded a square image the gallery will cut out the top and bottom part.

**Comment by atlantaluck** [comment]
On the individual page.  Please don't stretch the image, but make them look original to the uploaded image.

**Comment by saurabhd** [comment]
Ideal image resolution recommended is: 577*241px

**Comment by atlantaluck** [comment]
I think the thumb image is fine. but can we not make the big image not stretch. 
for example: for the posting under "can tho" with the picture of the white car.
The search results show thumb image is fine. but inside the individual post. the car look stretch.

**Comment by Deepali-AddWeb** [comment]
There are 3 possibilities to display an image in a specific slider resolution:
1) Image will be cropped from sides
2) Image will be stretched
3) Image can be displayed in centre with the blank space on sides.

Please confirm on how you want to display the image.

**Comment by atlantaluck** [comment]
I believed the thumb image is cropped right now correct? that's fine.  The big image inside the individual ads, you can do option 3 (centered with blank space on sides.).

**Comment by atlantaluck** [comment]
is this complete or not?

**Comment by Deepali-AddWeb** [comment]
Work is in progress. Will notify you once its completed.
