### ISSUE TITLE
Stock image if not image is uploaded

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#111]
Under “Post an ad” if no image is uploaded there will be a default image.   I will provide image.

**Comment by denisha-addweb** [comment]
Please provide image for same

**Comment by atlantaluck** [comment]
![no_image_thumb](https://cloud.githubusercontent.com/assets/17599998/14537681/0090b098-0246-11e6-97a3-65239f3e5622.gif)

**Comment by atlantaluck** [comment]
Please use this image.
