### ISSUE TITLE
Cannot see any of the “Quang Cao & Rao Vat” ads.

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#112]
I cannot see any of the “Quang Cao & Rao Vat” ads.

**Comment by denisha-addweb** [comment]
“Quang Cao & Rao Vat” ads working.
Note: please check your location(state) and ads location(state).

**Comment by atlantaluck** [comment]
There are no filters for "quang cao & rao vat" how can I select state.  The filter on the left is for "can tho" and "sang tiem" only.

**Comment by arpita-addweb** [comment]
We have implemented category filter . If you require state filter then please inform us.

**Comment by atlantaluck** [comment]
Yes, please implement the state filter just like the others.  Thanks
