### ISSUE TITLE
Sorting search results

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#114]
Please make the sorting box display after the search results.  The sorting box will # of listing will show like the example here.

http://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?sourceContext=carGurusHomePage_false_0&entitySelectingHelper.selectedEntity=&zip=30096

**Comment by atlantaluck** [comment]
1.  I cannot see state name for the current listings.
2.  Please move the sorting box to the top.  Thanks.

![sorting](https://cloud.githubusercontent.com/assets/17599998/14626448/6c65f49c-05b9-11e6-96bf-744d37f2d35d.jpg)

**Comment by saurabhd** [comment]
This would take 7 working hours. Need your approval for the same.

**Comment by atlantaluck** [comment]
![sorting](https://cloud.githubusercontent.com/assets/17599998/14638454/86829712-0605-11e6-970b-317bfcd7564f.jpg)

**Comment by atlantaluck** [comment]
As of currently there is no sorting of any kind on search results.  I see a sorting, but that is on the main page and serves no purpose.
