### ISSUE TITLE
Should we discuss issues for MOBILE display now?

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#121]
There are some adjustments I want to make.

**Comment by saurabhd** [comment]
Yes please, start adding issues here for mobile version too

**Comment by atlantaluck** [comment]
I'm using safari for iPhone.
1. Can we make the color logo ChomChom on top centered.
2. On the search results, can we move the body (description message) right below the posting title.  I've attached image.
![img_7925](https://cloud.githubusercontent.com/assets/17599998/14578949/03ac5972-0367-11e6-8235-9278e5c7b9f6.PNG)

**Comment by Deepali-AddWeb** [comment]
For point 2, Its not feasible to move the body (description message) right below the posting title in mobile display only. It can be moved in all the views, including desktop.
