### ISSUE TITLE
Seem like most of the functionalities will work and display correctly when logging in but not the regular test website.

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#122]
Display and functions are different when logged in than this site.

http://chomchomsqsuxmcnii.devcloud.acquia-sites.com/

**Comment by Deepali-AddWeb** [comment]
Ads are displayed based on location. Suppose you are in oregon & ads are added of oregon, then it will show up on pages of can-tho & sang-tiem, else no result will be displayed.
