### ISSUE TITLE
Change Filter Location

### ISSUE THREAD

**Issue by saurabhd** [Deepali-AddWeb/chomchom#125]
Additional approval of work: 

We need to do that - when user arrives, it should display the current location of user. But once he searches for different state then that location should change based on user's search.
If you remain on the same page [i.e can tho, sangtiem, etc] and refresh it then your results would remain same. for E.g: If you has searched for "Florida" then on refresh over the same page, results would be of florida only.but, once you click on "Homepage" or logo of chomchom, your results gets refreshed and you would get your location on top.

**Comment by atlantaluck** [comment]
I think the above issue is fixed.  But the "State filter I think there is a glitch.  I tried changing to a few different states and it is not updating correctly.

**Comment by saurabhd** [comment]
We have replicated one issue and have resolved. Check once and if you face any further issue, please provide scenario for the same.
