### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#127]
2 fixes are listed in the picture I've attached.  Also, I want to limit some of the characters for some fill in boxes.  So that the site won't be flooded.
![minor fixes](https://cloud.githubusercontent.com/assets/17599998/14666384/4b963224-06a7-11e6-8e40-8eefcdbe74d7.jpg)
  Once I have a complete list  I will add them here.

**Comment by atlantaluck** [comment]
The characters count for the Posting Title is really tricky.  On desktop we can probably go to 40, but on mobile the max is 22-27 I think before the "SAVE" button breaks down the the second line.  We no longer need the word "Posting Title : " on the title, so we have more room.

I see the backend where I can change it myself, but I don't want the mess things up yet.

Can Tho.
Title -40 (must evaluate to see if it work good for desktop and mobile)
Kinh Nghiem -25 characters
Contact name -30 characters
Tien luong -35 characters

Sang Tiem - Nails. can we ad commas for all integer & no decimal allow.
Title -40 (must evaluate to see if it work good for desktop and mobile)
Contact name-30
#Ghe -3
Monthly Rent-6
SQ/FT -6
#ban -20 (text field)
#tho -3
Shopping center -35
Monthly income -6 Missing this (must ad)
Price -8

Sang Tiem - Business for sale.
Type of business -35
Monthly income -6
Monthly Rent-6
SQ/FT -6
Price -8

**Comment by saurabhd** [comment]
Sang Tiem - Nails. can we ad commas for all integer & no decimal allow.

> > Let me know for which fields you require validations.

#ban -20 (text field)
Monthly income -6 Missing 

> > Let's keep this in pipeline as discussed over Skype.

can tho
Kinh Nghiem -25 characters

> > Making into 25 characters would not serve our purpose. What workaround I can suggest you is, we can provide limit to the number of options to be taken. 

For E.G: If Kinh Nghiệm: Tất Cả , Gel , Eyelashes , Facial , Làm Bột , Tay Chân Nước : it has 6 values. We can limit these values for your wish.

Tien luong -35 characters 
sang tiem nail
Monthly Rent-6
SQ/FT -6
#tho -3
Shopping center -35
Price -8Sang Tiem - Business for sale.
Monthly income -6
Monthly Rent-6
SQ/FT -6
Price -8

> > This is radio button and it allows 1 value at a time, so there is no need to place any limitations for characters. If we place these limitations than check this: http://chomchomsqsuxmcnii.devcloud.acquia-sites.com/sang-tiem , here you can see "Type Of Business : ... " - This would not look good. 

Let me know your thoughts for the same. 

Thanks!

**Comment by atlantaluck** [comment]
For now, just whatever that would look best.  I just don't want the website to be flooded on the main results display.

**Comment by atlantaluck** [comment]
For the Kinh Nghiem I want it to list everything: Tất Cả , Gel , Eyelashes , Facial , Làm Bột , Tay Chân Nước , Sẽ Đào Tạo , Wax.  
But can we fix the commas to this: Tất Cả, Gel, Eyelashes, Facial, Làm Bột, Tay Chân Nước, Sẽ Đào Tạo, Wax,

**Comment by atlantaluck** [comment]
I will check asap.

**Comment by atlantaluck** [comment]
1.  On the main search result page for "can tho" I still get 4 lines of description instead of just only 3.
2.  On the "Kinh Nghiem" display on the main search result page.  I want the preview to show everything including the display for "Điền Vào": Tất Cả, Gel, Eyelashes, Facial, Làm Bột, Tay Chân Nước, Sẽ Đào Tạo, Wax, (Điền Vào).

**Comment by saurabhd** [comment]
On the main search result page for "can tho" I still get 4 lines of description instead of just only 3.

> > This would depend upon screen resolution. 

On the "Kinh Nghiem" display on the main search result page. I want the preview to show everything including the display for "Điền Vào": Tất Cả, Gel, Eyelashes, Facial, Làm Bột, Tay Chân Nước, Sẽ Đào Tạo, Wax, (Điền Vào).

> > Would do and provide updates shortly.

**Comment by atlantaluck** [comment]
ok, I will wait for the update.  I will check out the website on different monitor sizes.

**Comment by atlantaluck** [comment]
On the main search result page for "can tho" I still get 4 lines of description instead of just only 3.

-- "This would depend upon screen resolution."

I've checked on both monitors, 13inch and 27inch, they are displaying the same 4 lines of exact information.  Please check on this for me.

**Comment by atlantaluck** [comment]
I tested 1 with the numbers and alphabet and it show 4 lines.  Then I tested another and it show 3 lines.  Not sure what's going on.

**Comment by atlantaluck** [comment]
let's not worry too much on this for now.  if you can fix it then good, if not we will come back later.

**Comment by saurabhd** [comment]
I tried some work around, please check and let me know your inputs.
