### ISSUE TITLE
Is the ad expiration notification working?

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#128]
Users should get a notification 10 days & 5 days & 1 day before the ad expires. Ad expiration is based on package selected. Default communication is email.  Customer will have option to be contacted my TEXT during registration.  Text will be send right away to verify it can receive TEXT.  We have Twilio.

**Comment by saurabhd** [comment]
We have implemented Twilio for SMS and email functionality but our subdomain  do not support this functionality. 

This would be accomplished once we move site to live. 

Further, please provide content for email and SMS template you require to display.

**Comment by atlantaluck** [comment]
Will update with that soon

**Comment by saurabhd** [comment]
Surely

**Comment by atlantaluck** [comment]
Please replace  information between *\* *\* with appropriate contents.  Here is the Email template.

Email subject: could be Posting Title.

Thank you for placing an ad with us. Your ad is now live at **URL LINK**

Your ad **TITLE OF POSTING** will run for **DURATION** days. We will remind you to renew your ad before it expires.

---

## Your Ad Summary

Ad Type: Sang Tiệm Nails **CATEGORY NAME**
Ad URL: 
Expiration Date: 2015-12-04 16:29:06
Price: $0.00

Notifications:
Your ad runs for **DURATION** days.  We'll send you an email reminders ten, five, & one days before your ad expires.

---

## How to Edit, Renew, or Remove Your Ad

You may edit, renew, or remove all your listings here: **URL LINK**

EDIT link: When you click edit you will be able to:
- Edit your price (if applicable)
- Edit your description
- Edit other ad details
- Edit your contact info
- Change your photos

## REMOVE link: When you click remove, your ad will be removed from our site.

If you have any questions, please call us Monday-Friday 10 a.m.-8 p.m. EST at 404-884-1888 or email raovat@chomchom.net.

We wish you the best of luck, and thanks again for using ChomChom.net.

Warm Regards,

chomchom.net
http://www.chomchom.net

**Comment by atlantaluck** [comment]
corrections: please ignore the *\* *\* comment and pay attention to the bold and CAPITALIZATION.

**Comment by atlantaluck** [comment]
sms sent after posting. 
SMS:

Thank you for posting your ad with chomchom.net.

**URL LINK**

Your ad will expires in **"DURATION"** days.

We will send you notifications before your ad expires.

**Comment by atlantaluck** [comment]
Corrections with Email template: 

Your ad TITLE OF POSTING will run for DURATION days. We will send you notifications before your ad expires.

**Comment by atlantaluck** [comment]
Question:  Do we have the ability to let the customer renew the ad before it expires.  Essentially, they still have to pay again, but it gives them an option the continues with the ad.

Thanks

**Comment by saurabhd** [comment]
Question: Do we have the ability to let the customer renew the ad before it expires. Essentially, they still have to pay again, but it gives them an option the continues with the ad.

> > No, you cannot renew ad before it expires. After Ad expires, renew button is activated in "My Account" page. 

Further, regarding Email templates: As discussed at #133, would proceed and let you know.
