### ISSUE TITLE
Email Template

### ISSUE THREAD

**Issue by saurabhd** [Deepali-AddWeb/chomchom#133]
Hello Jimmy,

PFA doc for email templates. Please check and confirm so that I can proceed accordingly.

Thanks! 
[EmailTemplates.pdf](https://github.com/Deepali-AddWeb/chomchom/files/238476/EmailTemplates.pdf)

**Comment by atlantaluck** [comment]
Yes, I think they are pretty standard for now.  We can always edit them later correct?
If so, then it is a go.  Thanks

**Comment by saurabhd** [comment]
Yes, you can edit it. Would incorporate these changes and let you know.

**Comment by saurabhd** [comment]
Have incorporated Email template content but can view it practically once we move over live.
