### ISSUE TITLE
EMAIL TO SELLER

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#23]
The form is not designed as per mock up the following points are 

1.The place Holder value should be small as per mock up images.
2. The Enter your message field should be small .
3. The term and condition check box should be checked by default .
4. The terms and condition content in not as per client mock up.
5. The send email label for the button should be small in size

**Comment by dharmesh-addweb** [comment]
Above all issues are solved except 3rd and 4th
3rd and 4th  is Functionality issue, so assigning to denisha
