### ISSUE TITLE
Filter : Drop Down 

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#24]
1.The colour for the fields in drop down doesn't match with the mock ups 
2. And the  font style  for the categories in the drop down should be as per the client 
3. Selected city should be highlighted with Bold and Black  font colour .
4. The search button label should be Bold .
5. The Reset Button label Font size should be small.
6. The fields  size in the drop down should be less
7. The label for the filter categories "Can Tho " and "San Tiem " its font style is different.

**Comment by dharmesh-addweb** [comment]
Above all issues are solved except 7th
7th is development issue, so assigning to denisha

**Comment by denisha-addweb** [comment]
7th is done
