### ISSUE TITLE
"Quang Cao & Rao Vat" has a different layout template

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#37]
Please check: I believe "quang cao & rao vat" has a different template than the "can tho" and "sang tiem".

**Comment by Deepali-AddWeb** [comment]
No different template generated for "quang cao & rao vat". Its currently kept same as of "can tho" and "sang tiem".

**Comment by atlantaluck** [comment]
template mockup is approved.
