### ISSUE TITLE
Business Directory : Detail page 

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#45]
1. Map and direction label  font colour is different and font size is different in mock up .
2. The phone image icon is missing.
3. The Edit Functionality given in the mock up is different which is given in the mock up .
4. The images in the thumbnail is not in same width and height (Note : give a proper width and height for all sizes of the images ).
5. The image displayed in the larger view is not as per the mock client mock in design .
6. The Thumbnail designed is not proper in design as per  psd's provided.

**Comment by dharmesh-addweb** [comment]
Above all issues are solved except 3rd, 4th, 5th, 6th
3rd, 4th, 5th, 6th development issue, so assigning to denisha
