### ISSUE TITLE
My Account : Locale Setting section 

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#53]
Time zone drop Down when scroll down will maximize in size and cover the whole webpage 

Note : Looks distorted , put a slider so that user can scroll down .

**Comment by dharmesh-addweb** [comment]
Above issues is development issue, so assigning to denisha

**Comment by arpita-addweb** [comment]
This functionality has been removed from the designer side (No more need in the site )
