### ISSUE TITLE
Can Tho : Posting Title 

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#63]
# Give proper Wrapping to the content in the title .
# In the Listing page the the title is not displayed .
# In the detail page the content moves  out of the border.

url : http://chomchomsqsuxmcnii.devcloud.acquia-sites.com/can-tho

**Comment by denisha-addweb** [comment]
url limit 74 litter more then 74 letter without space so it not display in detail page,
