### ISSUE TITLE
All Categories : Detail Page 

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#66]
Wrap the content if the content is more in length as it is colliding , looks distorted .

url : http://chomchomsqsuxmcnii.devcloud.acquia-sites.com/listing/job-listing-nails/lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum
![2016-03-10_1916](https://cloud.githubusercontent.com/assets/17269669/13671233/b46ddd7e-e6f4-11e5-944f-419643737c0a.png)

**Comment by denisha-addweb** [comment]
extra contain show next line using css
