### ISSUE TITLE
Anonymous User

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#76]
To  Save the Listings  for Anonymous User , Save functionality is not implemented .

Note : In the Documentation the client require  "Anonymous user can save ad listing. (Cookies will be used.)"

**Comment by Deepali-AddWeb** [comment]
We have used flag to save the listing & this is then displayed on user profile. We cannot make Anonymous user save listing, as there is no profile page for anonymous user. Also if we still make Anonymous user save listing, the listing will be removed as soon as the ip of user changes.
