### ISSUE TITLE
Responsive  Post An Add -> Choose a image 

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#86]
Responsive iPad , Browser (Safari)

Disable the Take a photo url when choose a image 
![img_1279](https://cloud.githubusercontent.com/assets/17269669/13808600/ee3e3084-eb8c-11e5-8b4e-5c5cd84a95fd.PNG)

**Comment by denisha-addweb** [comment]
default functionality for devices
