### ISSUE TITLE
Social Links 

### ISSUE THREAD

**Issue by arpita-addweb** [Deepali-AddWeb/chomchom#96]
Social Links implementation is pending .

**Comment by denisha-addweb** [comment]
We need social Links form client.

**Comment by atlantaluck** [comment]
https://www.facebook.com/chomchom.net/

Twitter: @chomchom_net

**Comment by denisha-addweb** [comment]
Please provide google+ link

**Comment by atlantaluck** [comment]
chomchom.net@gmail.com

**Comment by Deepali-AddWeb** [comment]
Please provide the google plus link to redirect to google plus page of chomchom, not gmail id. Here is an example: https://plus.google.com/+Addwebsolution

**Comment by atlantaluck** [comment]
https://plus.google.com/u/0/107107564431972578372/
